# Generated by Django 4.1.1 on 2022-09-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='img_url',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('appliances', 'Appliances'), ('grocery', 'Grocery')], max_length=64),
        ),
    ]
