# Generated by Django 4.1.1 on 2022-10-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_price_bid_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='won_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
