# Generated by Django 4.1.1 on 2022-12-09 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_likes_post_user_likes_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user_likes",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
